#pragma once

#define DEVICE_NAME         L"\\??\\DeleteProtector"
#define DRIVER_IOCTL_BASE   0x8208

#define IOCTL_KPROTECT_ADD_EXT \
    CTL_CODE(DRIVER_IOCTL_BASE, 0x800, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_KPROTECT_REMOVE_EXT \
    CTL_CODE(DRIVER_IOCTL_BASE, 0x801, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_KPROTECT_REMOVE_ALL \
    CTL_CODE(DRIVER_IOCTL_BASE, 0x802, METHOD_NEITHER, FILE_WRITE_ACCESS)